president_party = {
    "George Washington": "None",
    "John Adams": "Federalist",
    "Thomas Jefferson": "Democratic-Republican",
    "James Madison": "Democratic-Republican",
    "James Monroe": "Democratic-Republican",
    "John Quincy Adams": "Democratic-Republican",
    "Andrew Jackson": "Democrat",
    "Martin Van Buren": "Democrat",
    "William Henry Harrison": "Whig",
    "John Tyler": "Whig",
    "James K. Polk": "Democrat",
    "Zachary Taylor": "Whig",
    "Millard Fillmore": "Whig",
    "Franklin Pierce": "Democrat",
    "James Buchanan": "Democrat",
    "Abraham Lincoln": "Republican",
    "Andrew Johnson": "National Union",
    "Ulysses S. Grant": "Republican",
    "Rutherford B. Hayes": "Republican",
    "James A. Garfield": "Republican",
    "Chester A. Arthur": "Republican",
    "Grover Cleveland": "Democrat",
    "Benjamin Harrison": "Republican",
    "William McKinley": "Republican",
    "Theodore Roosevelt": "Republican",
    "William Howard Taft": "Republican",
    "Woodrow Wilson": "Democrat",
    "Warren G. Harding": "Republican",
    "Calvin Coolidge": "Republican",
    "Herbert Hoover": "Republican",
    "Franklin Roosevelt": "Democrat",
    "Harry S. Truman": "Democrat",
    "Dwight D. Eisenhower": "Republican",
    "John F. Kennedy": "Democrat",
    "Lyndon B. Johnson": "Democrat",
    "Richard M. Nixon": "Republican",
    "Gerald Ford": "Republican",
    "Jimmy Carter": "Democrat",
    "Ronald Reagan": "Republican",
    "George Bush": "Republican",
    "Bill Clinton": "Democrat",
    "George W. Bush": "Republican",
    "Barack Obama": "Democrat",
    "Donald Trump": "Republican",
    "Joe Biden": "Democrat"
}

