president_party = {
    "George Washington": "None",
    "John Adams": "Federalist",
    "Thomas Jefferson": "Democratic-Republican",
    "James Madison": "Democratic-Republican",
    "James Monroe": "Democratic-Republican",
    "John Quincy Adams": "Democratic-Republican",
    "Andrew Jackson": "Democrat",
    "Martin Van Buren": "Democrat",
    "William Henry Harrison": "Whig",
    "John Tyler": "Whig",
    "James K. Polk": "Democrat",
    "Zachary Taylor": "Whig",
    "Millard Fillmore": "Whig",
    "Franklin Pierce": "Democrat",
    "James Buchanan": "Democrat",
    "Abraham Lincoln": "Republican",
    "Andrew Johnson": "National Union",
    "Ulysses S. Grant": "Republican",
    "Rutherford B. Hayes": "Republican",
    "James A. Garfield": "Republican",
    "Chester A. Arthur": "Republican",
    "Grover Cleveland": "Democrat",
    "Benjamin Harrison": "Republican",
    "William McKinley": "Republican",
    "Theodore Roosevelt": "Republican",
    "William Howard Taft": "Republican",
    "Woodrow Wilson": "Democrat",
    "Warren G. Harding": "Republican",
    "Calvin Coolidge": "Republican",
    "Herbert Hoover": "Republican",
    "Franklin Roosevelt": "Democrat",
    "Harry S. Truman": "Democrat",
    "Dwight D. Eisenhower": "Republican",
    "John F. Kennedy": "Democrat",
    "Lyndon B. Johnson": "Democrat",
    "Richard M. Nixon": "Republican",
    "Gerald Ford": "Republican",
    "Jimmy Carter": "Democrat",
    "Ronald Reagan": "Republican",
    "George Bush": "Republican",
    "Bill Clinton": "Democrat",
    "George W. Bush": "Republican",
    "Barack Obama": "Democrat",
    "Donald Trump": "Republican",
    "Joe Biden": "Democrat"
}

justices_appointed_by_president = {
    "John Jay": {"President": "George Washington", "Year": 1789},
    "James Wilson": {"President": "George Washington", "Year": 1789},
    "John Rutledge": {"President": "George Washington", "Year": 1790},
    "William Cushing": {"President": "George Washington", "Year": 1790},
    "John Blair": {"President": "George Washington", "Year": 1790},
    "James Iredell": {"President": "George Washington", "Year": 1790},
    "Thomas Johnson": {"President": "George Washington", "Year": 1791},
    "William Paterson": {"President": "George Washington", "Year": 1793},
    "John Rutledge (2nd Appt)": {"President": "George Washington", "Year": 1795},
    "Oliver Ellsworth": {"President": "George Washington", "Year": 1796},
    "Samuel Chase": {"President": "George Washington", "Year": 1796},
    "Bushrod Washington": {"President": "John Adams", "Year": 1798},
    "Alfred Moore": {"President": "John Adams", "Year": 1800},
    "John Marshall": {"President": "John Adams", "Year": 1801},
    "William Johnson": {"President": "Thomas Jefferson", "Year": 1804},
    "Brockholst Livingston": {"President": "Thomas Jefferson", "Year": 1807},
    "Thomas Todd": {"President": "Thomas Jefferson", "Year": 1807},
    "Gabriel Duvall": {"President": "James Madison", "Year": 1811},
    "Joseph Story": {"President": "James Madison", "Year": 1812},
    "Smith Thompson": {"President": "James Monroe", "Year": 1823},
    "Robert Trimble": {"President": "John Quincy Adams", "Year": 1826},
    "John McLean": {"President": "Andrew Jackson", "Year": 1829},
    "Henry Baldwin": {"President": "Andrew Jackson", "Year": 1830},
    "James Moore Wayne": {"President": "Andrew Jackson", "Year": 1835},
    "Roger Brooke Taney": {"President": "Andrew Jackson", "Year": 1836},
    "Philip Pendleton Barbour": {"President": "Andrew Jackson", "Year": 1836},
    "John Catron": {"President": "Andrew Jackson", "Year": 1837},
    "John McKinley": {"President": "Martin Van Buren", "Year": 1838},
    "Peter Vivian Daniel": {"President": "Martin Van Buren", "Year": 1842},
    "Samuel Nelson": {"President": "John Tyler", "Year": 1845},
    "Levi Woodbury": {"President": "James K. Polk", "Year": 1845},
    "Robert Cooper Grier": {"President": "James K. Polk", "Year": 1846},
    "Benjamin Robbins Curtis": {"President": "Millard Fillmore", "Year": 1851},
    "John Archibald Campbell": {"President": "Franklin Pierce", "Year": 1853},
    "Nathan Clifford": {"President": "James Buchanan", "Year": 1858},
    "Noah Haynes Swayne": {"President": "Abraham Lincoln", "Year": 1862},
    "Samuel Freeman Miller": {"President": "Abraham Lincoln", "Year": 1862},
    "David Davis": {"President": "Abraham Lincoln", "Year": 1862},
    "Stephen Johnson Field": {"President": "Abraham Lincoln", "Year": 1863},
    "Salmon Portland Chase": {"President": "Abraham Lincoln", "Year": 1864},
    "William Strong": {"President": "Ulysses S. Grant", "Year": 1870},
    "Joseph P. Bradley": {"President": "Ulysses S. Grant", "Year": 1870},
    "Ward Hunt": {"President": "Ulysses S. Grant", "Year": 1873},
    "Morrison Remick Waite": {"President": "Ulysses S. Grant", "Year": 1874},
    "John Marshall Harlan": {"President": "Rutherford B. Hayes", "Year": 1877},
    "William Burnham Woods": {"President": "Rutherford B. Hayes", "Year": 1881},
    "Stanley Matthews": {"President": "James A. Garfield", "Year": 1881},
    "Horace Gray": {"President": "Chester A. Arthur", "Year": 1882},
    "Samuel Blatchford": {"President": "Chester A. Arthur", "Year": 1882},
    "Melville Weston Fuller": {"President": "Grover Cleveland", "Year": 1888},
    "Lucius Quintus C. Lamar": {"President": "Grover Cleveland", "Year": 1888},
    "David Josiah Brewer": {"President": "Benjamin Harrison", "Year": 1890},
    "Henry Billings Brown": {"President": "Benjamin Harrison", "Year": 1891},
    "George Shiras": {"President": "Benjamin Harrison", "Year": 1892},
    "Howell Edmunds Jackson": {"President": "Benjamin Harrison", "Year": 1893},
    "Edward Douglass White": {"President": "Grover Cleveland", "Year": 1894},
    "Rufus Wheeler Peckham": {"President": "Grover Cleveland", "Year": 1896},
    "Joseph McKenna": {"President": "William McKinley", "Year": 1898},
    "Oliver Wendell Holmes": {"President": "Theodore Roosevelt", "Year": 1902},
    "William Rufus Day": {"President": "Theodore Roosevelt", "Year": 1903},
    "William Henry Moody": {"President": "Theodore Roosevelt", "Year": 1906},
    "Edward Douglass White": {"President": "Edward Douglass White", "Year": 1910},
    "Horace Harmon Lurton": {"President": "Edward Douglass White", "Year": 1910},
    "Charles Evans Hughes": {"President": "Edward Douglass White", "Year": 1910},
    "Willis Van Devanter": {"President": "Edward Douglass White", "Year": 1911},
    "Joseph Rucker Lamar": {"President": "Edward Douglass White", "Year": 1911},
    "Mahlon Pitney": {"President": "Edward Douglass White", "Year": 1912},
    "James Clark McReynolds": {"President": "Woodrow Wilson", "Year": 1914},
    "Louis Dembitz Brandeis": {"President": "Woodrow Wilson", "Year": 1916},
    "John Hessin Clarke": {"President": "Woodrow Wilson", "Year": 1916},
    "William Howard Taft": {"President": "Warren G. Harding", "Year": 1921},
    "George Sutherland": {"President": "Warren G. Harding", "Year": 1922},
    "Pierce Butler": {"President": "Warren G. Harding", "Year": 1923},
    "Edward Terry Sanford": {"President": "Warren G. Harding", "Year": 1923},
    "Harlan Fiske Stone": {"President": "Calvin Coolidge", "Year": 1925},
    "Charles Evans Hughes": {"President": "Herbert Hoover", "Year": 1930},
    "Owen Josephus Roberts": {"President": "Herbert Hoover", "Year": 1930},
    "Benjamin Nathan Cardozo": {"President": "Herbert Hoover", "Year": 1932},
    "Hugo Lafayette Black": {"President": "Franklin D. Roosevelt", "Year": 1937},
    "Stanley Forman Reed": {"President": "Franklin D. Roosevelt", "Year": 1938},
    "Felix Frankfurter": {"President": "Franklin D. Roosevelt", "Year": 1939},
    "William Orville Douglas": {"President": "Franklin D. Roosevelt", "Year": 1939},
    "Frank Murphy": {"President": "Franklin D. Roosevelt", "Year": 1940},
    "Harlan Fiske Stone": {"President": "Franklin D. Roosevelt", "Year": 1941},
    "James Francis Byrnes": {"President": "Franklin D. Roosevelt", "Year": 1941},
    "Robert Houghwout Jackson": {"President": "Franklin D. Roosevelt", "Year": 1941},
    "Wiley Blount Rutledge": {"President": "Franklin D. Roosevelt", "Year": 1943},
    "Harold Hitz Burton": {"President": "Harry S. Truman", "Year": 1945},
    "Fred Moore Vinson": {"President": "Harry S. Truman", "Year": 1946},
    "Tom Campbell Clark": {"President": "Harry S. Truman", "Year": 1949},
    "Sherman Minton": {"President": "Harry S. Truman", "Year": 1949},
    "Earl Warren": {"President": "Dwight D. Eisenhower", "Year": 1953},
    "John Marshall Harlan II": {"President": "Dwight D. Eisenhower", "Year": 1955},
    "William J. Brennan Jr.": {"President": "Dwight D. Eisenhower", "Year": 1956},
    "Charles Evans Whittaker": {"President": "Dwight D. Eisenhower", "Year": 1957},
    "Potter Stewart": {"President": "Dwight D. Eisenhower", "Year": 1958},
    "Byron White": {"President": "John F. Kennedy", "Year": 1962},
    "Arthur Goldberg": {"President": "John F. Kennedy", "Year": 1962},
    "Abe Fortas": {"President": "Lyndon B. Johnson", "Year": 1965},
    "Thurgood Marshall": {"President": "Lyndon B. Johnson", "Year": 1967},
    "Warren E. Burger": {"President": "Richard M. Nixon", "Year": 1969},
    "Harry A. Blackmun": {"President": "Richard M. Nixon", "Year": 1970},
    "Lewis F. Powell Jr.": {"President": "Richard M. Nixon", "Year": 1972},
    "William H. Rehnquist": {"President": "Richard M. Nixon", "Year": 1972},
    "John Paul Stevens": {"President": "Gerald Ford", "Year": 1975},
    "Sandra Day O'Connor": {"President": "Ronald Reagan", "Year": 1981},
    "William H. Rehnquist (Chief Justice)": {"President": "Ronald Reagan", "Year": 1986},
    "Antonin Scalia": {"President": "Ronald Reagan", "Year": 1986},
    "Anthony M. Kennedy": {"President": "Ronald Reagan", "Year": 1988},
    "David H. Souter": {"President": "George H. W. Bush", "Year": 1990},
    "Clarence Thomas": {"President": "George H. W. Bush", "Year": 1991},
    "Ruth Bader Ginsburg": {"President": "Bill Clinton", "Year": 1993},
    "Stephen G. Breyer": {"President": "Bill Clinton", "Year": 1994},
    "John G. Roberts (Chief Justice)": {"President": "George W. Bush", "Year": 2005},
    "Samuel A. Alito Jr.": {"President": "George W. Bush", "Year": 2006},
    "Sonia Sotomayor": {"President": "Barack Obama", "Year": 2009},
    "Elena Kagan": {"President": "Barack Obama", "Year": 2010},
    "Neil M. Gorsuch": {"President": "Donald Trump", "Year": 2017},
    "Brett M. Kavanaugh": {"President": "Donald Trump", "Year": 2018},
    "Amy Coney Barrett": {"President": "Donald Trump", "Year": 2020},
}


